openapi: 3.0.0
info:
  version: 1.0.0
  title: Community Forum Server API
  description: Server API for the Community Forum

paths:
  /register:
    post:
      summary: registers a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  error:
                    type: string
  /boards:
    get:
      summary: Returns a list of all boards
      responses:
        '200':
          description: JSON array of boards
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Board'
    post:
      summary: Creates a new Board

      responses:
components:
  schemas:
    Board:
      type: object
      properties:
        _id:
          type: string
          readOnly: true
          description: UID generated by mongodb
        boardName:
          type: string
          description: Name of the board
        boardDescription:
          type: string
          description: Description of the board
      required:
        - boardName
        - boardDescription
    User:
      type: object
      properties:
        _id:
          type: string
          readOnly: true
          description: UID generated by mongodb
        username:
          type: string
        email:
          type: string
        password:
          type: string
          writeOnly: true
      required:
        - username
        - email
        - password
    Post:
      type: object
      properties:
        _id:
          type: string
          readOnly: true
          description: UID generated by mongodb
        boardID:
          type: string
          description: foreign key from Board
        authorID:
          type: string
          description: foreign key from User
        timestamp:
          type: string
          readOnly: true
          description: UTC timestamp
        title:
          type: string
      required:
        - boardID
        - authorID
        - timestamp