name: Build and Deploy

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build App Dockerfile
        run: docker build -t ${{ vars.DOCKERHUB_USER }}/app ./app

      - name: Build Server Dockerfile
        run: docker build -t ${{ vars.DOCKERHUB_USER }}/server ./server

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: docker login -u ${{ vars.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_KEY }}

      - name: Deploy App Dockerfile
        run: docker push ${{ vars.DOCKERHUB_USER }}/app

      - name: Deploy Server Dockerfile
        run: docker push ${{ vars.DOCKERHUB_USER }}/server
        
