name: Test Server

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: node:20-bullseye

    steps:
      - uses: actions/checkout@v4

      - run: npm ci
        working-directory: ./server
      - run: npm run build --if-present
        working-directory: ./server
      - run: npm test
        working-directory: ./server
