name: Test Server

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v4

      - name: Download OpenSSL 1.1
        run: wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
        
      - name: Install OpenSSL 1.1
        run: sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - run: npm ci
      - run: npm test
