name: Test Server

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./server

    steps:
      - uses: actions/checkout@v4

      - name: Install OpenSSL 1.1
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          
      - run: npm ci
        working-directory: ./server
      - run: npm run build --if-present
        working-directory: ./server
      - run: npm test
        working-directory: ./server
